# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('buzzfeed', models.IntegerField(default=1)),
                ('daily_mail', models.IntegerField(default=1)),
                ('entertainment_weekly', models.IntegerField(default=1)),
                ('ign', models.IntegerField(default=1)),
                ('mashable', models.IntegerField(default=1)),
                ('mtv_news', models.IntegerField(default=1)),
                ('polygon', models.IntegerField(default=1)),
                ('the_lad_bible', models.IntegerField(default=1)),
                ('ars_technica', models.IntegerField(default=1)),
                ('crypto_coins_news', models.IntegerField(default=1)),
                ('engadget', models.IntegerField(default=1)),
                ('hacker_news', models.IntegerField(default=1)),
                ('recode', models.IntegerField(default=1)),
                ('t3n', models.IntegerField(default=1)),
                ('techcrunch', models.IntegerField(default=1)),
                ('techradar', models.IntegerField(default=1)),
                ('the_next_web', models.IntegerField(default=1)),
                ('the_verge', models.IntegerField(default=1)),
                ('wired', models.IntegerField(default=1)),
            ],
        ),
    ]
