# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='gruenderszene',
            field=models.IntegerField(default=1),
        ),
    ]
