# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_gruenderszene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='engadget',
        ),
        migrations.RemoveField(
            model_name='news',
            name='gruenderszene',
        ),
        migrations.RemoveField(
            model_name='news',
            name='t3n',
        ),
    ]
