# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
