# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
