# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='signups',
            field=models.IntegerField(default=100),
        ),
    ]
