# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
