# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180312_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
