# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-15 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_ratings_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='edited',
            field=models.IntegerField(default=0),
        ),
    ]
