# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feed',
        ),
    ]
